# Generated by Django 2.2.6 on 2019-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191031_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Carpet Cleaning (Houses)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CC', 'Carpet Cleaning (Houses)'), ('CCT', 'Carpet Cleaning (Townhouses Includes 15 Stairs)'), ('CCU', 'Carpet Cleaning (Units & Apartments)'), ('CCO', 'Carpet Cleaning (Offices/Commercial)'), ('MC', 'Mattress Cleaning'), ('SC', 'Sofa Cleaning'), ('RC', 'Rug Cleaning (On-site At Your Premises)'), ('AA', 'Anti Allergen Treatment')], max_length=2),
        ),
    ]
