# Generated by Django 2.2.6 on 2019-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191101_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CC', 'Carpet Cleaning (Houses)'), ('CCT', 'Carpet Cleaning (Townhouses Includes 15 Stairs)'), ('CCU', 'Carpet Cleaning (Units & Apartments)'), ('CCO', 'Carpet Cleaning (Offices/Commercial)'), ('MC', 'Mattress Cleaning'), ('SC', 'Sofa Cleaning'), ('RC', 'Rug Cleaning (On-site At Your Premises)'), ('AA', 'Anti Allergen Treatment')], max_length=3),
        ),
    ]
