from django.urls import path

from django.views.generic import TemplateView
from .views import (
    AddCouponView,
    AddCommentView,
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    PaymentView,
    remove_single_item_from_cart
    
)


urlpatterns = [
    path('', AddCommentView.as_view(template_name="myapp/index.html"), name='index'),
    path('about/', TemplateView.as_view(template_name='myapp/about.html'), name='about'),
    path('accreditations/', TemplateView.as_view(template_name='myapp/accreditations.html'), name='accreditations'),
    path('adelaide/', TemplateView.as_view(template_name='myapp/adelaide.html'), name='adelaide'),
    path('anti_allergen_cleaning/', TemplateView.as_view(template_name='myapp/anti_allergen_cleaning.html'), name='anti_allergen_cleaning'),
    path('appointment/', TemplateView.as_view(template_name='myapp/appointment.html'), name='appointment'),
    path('brisbane/', TemplateView.as_view(template_name='myapp/brisbane.html'), name='brisbane'),
    path('canberra/', TemplateView.as_view(template_name='myapp/canberra.html'), name='canberra'),
    path('carpet_cleaning_adelaide/', TemplateView.as_view(template_name='myapp/carpet_cleaning_adelaide.html'), name='carpet_cleaning_adelaide'),
    path('carpet_cleaning_brisbane/', TemplateView.as_view(template_name='myapp/carpet_cleaning_brisbane.html'), name='carpet_cleaning_brisbane'),
    path('carpet_cleaning_canberra/', TemplateView.as_view(template_name='myapp/carpet_cleaning_canberra.html'), name='carpet_cleaning_canberra'),
    path('carpet_cleaning_melbourne/', TemplateView.as_view(template_name='myapp/carpet_cleaning_melbourne.html'), name='carpet_cleaning_melbourne'),
    path('carpet_cleaning_newcastle/', TemplateView.as_view(template_name='myapp/carpet_cleaning_newcastle.html'), name='carpet_cleaning_newcastle'),
    path('carpet_cleaning_sydney/', TemplateView.as_view(template_name='myapp/carpet_cleaning_sydney.html'), name='carpet_cleaning_sydney'),
    path('carpet_cleaning_wollongong/', TemplateView.as_view(template_name='myapp/carpet_cleaning_wollongong.html'), name='carpet_cleaning_wollongong'),
    path('carpet_dry_clean/', TemplateView.as_view(template_name='myapp/carpet_dry_clean.html'), name='carpet_dry_clean'),
    path('carpet_steam_cleaning/', TemplateView.as_view(template_name='myapp/carpet_steam_cleaning.html'), name='carpet_steam_cleaning'),
    path('cleaning_agents/', TemplateView.as_view(template_name='myapp/cleaning_agents.html'), name='cleaning_agents'),
    path('faq/', TemplateView.as_view(template_name='myapp/faq.html'), name='faq'),
    path('contact/', TemplateView.as_view(template_name='myapp/base-admin.html'), name='contact'),
    path('filtration_soiling/', TemplateView.as_view(template_name='myapp/filtration_soiling.html'), name='filtration_soiling'),
    path('goldcoast/', TemplateView.as_view(template_name='myapp/goldcoast.html'), name='goldcoast'),
    path('heavy_soiled_carpets/', TemplateView.as_view(template_name='myapp/heavy_soiled_carpets.html'), name='heavy_soiled_carpets'),
    path('instant_quote/', TemplateView.as_view(template_name='myapp/instant_quote.html'), name='instant_quote'),
    path('leather_sofa_leaning/', TemplateView.as_view(template_name='myapp/leather_sofa_leaning.html'), name='leather_sofa_leaning'),
    path('mattress_cleaning_adelaide/', TemplateView.as_view(template_name='myapp/mattress_cleaning_adelaide.html'), name='mattress_cleaning_adelaide'),
    path('mattress_cleaning_brisbane/', TemplateView.as_view(template_name='myapp/mattress_cleaning_brisbane.html'), name='mattress_cleaning_brisbane'),
    path('mattress_cleaning_canberra/', TemplateView.as_view(template_name='myapp/mattress_cleaning_canberra.html'), name='mattress_cleaning_canberra'),
    path('mattress_cleaning_gold_coast/', TemplateView.as_view(template_name='myapp/mattress_cleaning_gold_coast.html'), name='mattress_cleaning_gold_coast'),
    path('mattress_cleaning_melbourne/', TemplateView.as_view(template_name='myapp/mattress_cleaning_melbourne.html'), name='mattress_cleaning_melbourne'),
    path('mattress_cleaning_newcastle/', TemplateView.as_view(template_name='myapp/mattress_cleaning_newcastle.html'), name='mattress_cleaning_newcastle'),
    path('mattress_cleaning_sydney/', TemplateView.as_view(template_name='myapp/mattress_cleaning_sydney.html'), name='mattress_cleaning_sydney'),
    path('mattress_cleaning_wollongong/', TemplateView.as_view(template_name='myapp/mattress_cleaning_wollongong.html'), name='mattress_cleaning_wollongong'),
    path('mattress_cleaning/', TemplateView.as_view(template_name='myapp/mattress_cleaning.html'), name='mattress_cleaning'),
    path('melbourne/', TemplateView.as_view(template_name='myapp/melbourne.html'), name='melbourne'),
    path('newcastle/', TemplateView.as_view(template_name='myapp/newcastle.html'), name='newcastle'),
    path('perth/', TemplateView.as_view(template_name='myapp/perth.html'), name='perth'),
    path('pet_stains_treatments/', TemplateView.as_view(template_name='myapp/pet_stains_treatments.html'), name='pet_stains_treatments'),
    path('privacy_policy/', TemplateView.as_view(template_name='myapp/privacy_policy.html'), name='privacy_policy'),
    path('rug_cleaning_adelaide/', TemplateView.as_view(template_name='myapp/rug_cleaning_adelaide.html'), name='rug_cleaning_adelaide'),
    path('rug_cleaning_brisbane/', TemplateView.as_view(template_name='myapp/rug_cleaning_brisbane.html'), name='rug_cleaning_brisbane'),
    path('rug_cleaning_canberra/', TemplateView.as_view(template_name='myapp/rug_cleaning_canberra.html'), name='rug_cleaning_canberra'),
    path('rug_cleaning_gold_coast/', TemplateView.as_view(template_name='myapp/base-admin.html'), name='rug_cleaning_gold_coast'),
    path('rug_cleaning_melbourne/', TemplateView.as_view(template_name='myapp/rug_cleaning_melbourne.html'), name='rug_cleaning_melbourne'),
    path('rug_cleaning_newcastle/', TemplateView.as_view(template_name='myapp/rug_cleaning_newcastle.html'), name='rug_cleaning_newcastle'),
    path('rug_cleaning_sydney/', TemplateView.as_view(template_name='myapp/rug_cleaning_sydney.html'), name='rug_cleaning_sydney'),
    path('rug_cleaning_wollongong/', TemplateView.as_view(template_name='myapp/rug_cleaning_wollongong.html'), name='rug_cleaning_wollongong'),
    path('rug_cleaning/', TemplateView.as_view(template_name='myapp/rug_cleaning.html'), name='rug_cleaning'),
    path('service/', TemplateView.as_view(template_name='myapp/service.html'), name='service'),
    path('sofa_cleaning_brisbane/', TemplateView.as_view(template_name='myapp/sofa_cleaning_brisbane.html'), name='sofa_cleaning_brisbane'),
    path('sofa_cleaning_gold_coast/', TemplateView.as_view(template_name='myapp/sofa_cleaning_gold_coast.html'), name='sofa_cleaning_gold_coast'),
    path('fabric_sofa_cleaning/', TemplateView.as_view(template_name='myapp/fabric_sofa_cleaning.html'), name='fabric_sofa_cleaning'),
    path('sydney/', TemplateView.as_view(template_name='myapp/sydney.html'), name='sydney'),
    path('terms_and_conditions/', TemplateView.as_view(template_name='myapp/terms_and_conditions.html'), name='terms_and_conditions'),
    path('tile_and_grout_cleaning/', TemplateView.as_view(template_name='myapp/tile_and_grout_cleaning.html'), name='tile_and_grout_cleaning'),
    path('tile_cleaning_gold_coast/', TemplateView.as_view(template_name='myapp/tile_cleaning_gold_coast.html'), name='tile_cleaning_gold_coast'),
    path('upholstery_cleaning_melbourne/', TemplateView.as_view(template_name='myapp/upholstery_cleaning_melbourne.html'), name='upholstery_cleaning_melbourne'),
    path('water_damage_adelaide/', TemplateView.as_view(template_name='myapp/water_damage_adelaide.html'), name='water_damage_adelaide'),
    path('water_damage_brisbane/', TemplateView.as_view(template_name='myapp/water_damage_brisbane.html'), name='water_damage_brisbane'),
    path('water_damage_canberra/', TemplateView.as_view(template_name='myapp/water_damage_canberra.html'), name='water_damage_canberra'),
    path('water_damage_gold_coast/', TemplateView.as_view(template_name='myapp/water_damage_gold_coast.html'), name='water_damage_gold_coast'),
    path('water_damage_melbourne/', TemplateView.as_view(template_name='myapp/water_damage_melbourne.html'), name='water_damage_melbourne'),
    path('water_damage_newcastle/', TemplateView.as_view(template_name='myapp/water_damage_newcastle.html'), name='water_damage_newcastle'),
    path('water_damage_sydney/', TemplateView.as_view(template_name='myapp/water_damage_sydney.html'), name='water_damage_sydney'),
    path('water_damage_wollongong/', TemplateView.as_view(template_name='myapp/water_damage_wollongong.html'), name='water_damage_wollongong'),
    path('water_damage/', TemplateView.as_view(template_name='myapp/water_damage.html'), name='water_damage'),
    path('wollongong/', TemplateView.as_view(template_name='myapp/wollongong.html'), name='wollongong'),
    path('Enter valid Url/', TemplateView.as_view(template_name='myapp/Enter valid Url.html'), name='Enter valid Url'),
    path('cleanto/index/', TemplateView.as_view(template_name='myapp/cleanto/index.html'), name='inde'),
    path('cleanto/admin/', TemplateView.as_view(template_name='myapp//cleanto/Please enter google calender admin url.html'), name='calender'),
    path('cleanto/frontend/', TemplateView.as_view(template_name='myapp/cleanto/Please enter google calender frontend url.html'), name='frontend'),
    path('cleanto/', HomeView.as_view() , name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    #path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),

    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),


]